services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    hostname: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - CUSTOM_USER=ibd
      - PASSWORD=ibd2026
    volumes:
      - ./config:/config
    ports:
      - 443:3001
    shm_size: "2gb"
    restart: unless-stopped
    networks:
      - default
      - hadoopnet

networks:
  hadoopnet:
    external: true
    name: hadoop_hadoopnet