services:
  firefox:
    image: jlesage/firefox
    container_name: firefox
    restart: unless-stopped
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/Madrid
      - KEEP_APP_RUNNING=1
      - SECURE_CONNECTION=1
      - WEB_AUTHENTICATION=1
      - WEB_AUTHENTICATION_USERNAME=ibd
      - WEB_AUTHENTICATION_PASSWORD=ibd2026
    ports:
      - 443:5800
    volumes:
      - ./config:/config:rw
